kind: pipeline
type: ssh
name: deploy

trigger:
  branch:
    - master

server:
  host:
    from_secret: host
  user: deploy
  password:
    from_secret: password

steps:
  - name: pull
    commands:
      - cd /srv/wordpress/themes/reitz-wordpress-theme/
      - git pull origin master

